spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/postgres?currentSchema=learningspring
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5000
springdoc:
  swagger-ui:
    path: /swagger
